-- 补齐计量基础数据与新模块写权限。
CREATE TABLE IF NOT EXISTS qms.calibration_agency (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agency_name VARCHAR(128) NOT NULL,
  certificate_no VARCHAR(64),
  contact_name VARCHAR(64),
  contact_phone VARCHAR(64),
  qualification_expiry_date DATE,
  status VARCHAR(16) NOT NULL DEFAULT '有效',
  remark TEXT,
  plant_code VARCHAR(8) NOT NULL,
  plant_name VARCHAR(32) NOT NULL,
  created_by VARCHAR(64), updated_by VARCHAR(64),
  is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (agency_name, plant_code)
);

INSERT INTO qms.sys_role_permission(role_code,module_code,action_code,created_at,updated_at,is_deleted)
SELECT r.role_code,m.module_code,'EDIT',NOW(),NOW(),0
FROM qms.sys_role r CROSS JOIN (VALUES ('afterSales'),('measurement'),('qualitySystem')) m(module_code)
WHERE r.role_code IN ('R04','R06') AND r.is_deleted=0
AND NOT EXISTS(SELECT 1 FROM qms.sys_role_permission p WHERE p.role_code=r.role_code AND p.module_code=m.module_code AND p.action_code='EDIT' AND p.is_deleted=0);

INSERT INTO qms.sys_role_permission(role_code,module_code,action_code,created_at,updated_at,is_deleted)
SELECT r.role_code,'measurement','EDIT',NOW(),NOW(),0 FROM qms.sys_role r
WHERE r.role_code='R02' AND r.is_deleted=0
AND NOT EXISTS(SELECT 1 FROM qms.sys_role_permission p WHERE p.role_code=r.role_code AND p.module_code='measurement' AND p.action_code='EDIT' AND p.is_deleted=0);
