-- 售后工单与客户满意度（QMS 内部手工维护）
CREATE TABLE IF NOT EXISTS qms.after_sales_work_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(48) NOT NULL,
    customer_name VARCHAR(128) NOT NULL,
    customer_contact VARCHAR(64),
    customer_phone VARCHAR(32),
    service_type VARCHAR(16) NOT NULL,
    product_code VARCHAR(64),
    product_name VARCHAR(128),
    product_batch_no VARCHAR(64),
    fault_description TEXT,
    service_address VARCHAR(256),
    assignee_name VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT '新建',
    visit_record TEXT,
    close_signature VARCHAR(64),
    close_time TIMESTAMP,
    plant_code VARCHAR(8) NOT NULL,
    plant_name VARCHAR(32) NOT NULL,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (order_no)
);
CREATE TABLE IF NOT EXISTS qms.after_sales_work_order_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    before_status VARCHAR(16), after_status VARCHAR(16) NOT NULL,
    operator_name VARCHAR(64), remark TEXT,
    plant_code VARCHAR(8) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS qms.customer_satisfaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
    reason_dimension VARCHAR(64), follow_up_result TEXT,
    responsible_name VARCHAR(64), follow_up_time TIMESTAMP,
    capa_no VARCHAR(64),
    plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (work_order_id)
);
CREATE INDEX IF NOT EXISTS idx_after_sales_order_plant_status ON qms.after_sales_work_order(plant_code, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_after_sales_log_order ON qms.after_sales_work_order_log(work_order_id, created_at);
INSERT INTO qms.sys_module (module_code, module_name, status, created_at, updated_at, is_deleted)
SELECT 'afterSales', '售后管理', '1', NOW(), NOW(), 0
WHERE NOT EXISTS (SELECT 1 FROM qms.sys_module WHERE module_code = 'afterSales' AND is_deleted = 0);
INSERT INTO qms.sys_role_permission (role_code, module_code, action_code, created_at, updated_at, is_deleted)
SELECT r.role_code, 'afterSales', 'VIEW', NOW(), NOW(), 0 FROM qms.sys_role r
WHERE r.is_deleted = 0 AND NOT EXISTS (SELECT 1 FROM qms.sys_role_permission p WHERE p.role_code = r.role_code AND p.module_code = 'afterSales' AND p.action_code = 'VIEW' AND p.is_deleted = 0);
