CREATE TABLE IF NOT EXISTS qms.instrument_calibration_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id BIGINT NOT NULL,
  plan_date DATE NOT NULL,
  agency VARCHAR(128), responsible_name VARCHAR(64),
  status VARCHAR(16) NOT NULL DEFAULT '待执行',
  completed_at TIMESTAMP,
  plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL,
  created_by VARCHAR(64), updated_by VARCHAR(64),
  is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_calibration_task_due ON qms.instrument_calibration_task(plant_code,status,plan_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_open_calibration_task ON qms.instrument_calibration_task(instrument_id) WHERE status IN ('待执行','逾期') AND is_deleted=0;
