-- 计量器具全生命周期（台账、校准、使用、借还、维修、报废）
CREATE TABLE IF NOT EXISTS qms.measuring_instrument (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instrument_code VARCHAR(64) NOT NULL, instrument_name VARCHAR(128) NOT NULL,
 model VARCHAR(64), specification VARCHAR(128), accuracy_grade VARCHAR(64), measurement_range VARCHAR(128), factory_serial_no VARCHAR(64), manufacturer VARCHAR(128), purchase_date DATE,
 department_name VARCHAR(64), storage_location VARCHAR(128), keeper_name VARCHAR(64), status VARCHAR(16) NOT NULL DEFAULT '合格可用', calibration_cycle_months INTEGER NOT NULL DEFAULT 12,
 calibration_agency VARCHAR(128), last_calibration_date DATE, next_calibration_date DATE, remark TEXT, qr_code VARCHAR(128),
 plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL, created_by VARCHAR(64), updated_by VARCHAR(64), is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW(), UNIQUE(instrument_code, plant_code));
CREATE TABLE IF NOT EXISTS qms.instrument_calibration_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instrument_id BIGINT NOT NULL, plan_date DATE, calibration_date DATE, result VARCHAR(16), agency VARCHAR(128), certificate_no VARCHAR(64), valid_until DATE, responsible_name VARCHAR(64), remark TEXT,
 plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL, created_by VARCHAR(64), updated_by VARCHAR(64), is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qms.instrument_usage_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instrument_id BIGINT NOT NULL, work_order_no VARCHAR(64), product_batch_no VARCHAR(64), process_name VARCHAR(128), inspection_record_no VARCHAR(64), measurement_item VARCHAR(128), measured_value VARCHAR(128), measurement_unit VARCHAR(32), operator_name VARCHAR(64), used_at TIMESTAMP NOT NULL DEFAULT NOW(),
 plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL, created_by VARCHAR(64), is_deleted SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qms.instrument_lending_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instrument_id BIGINT NOT NULL, borrower_name VARCHAR(64) NOT NULL, purpose TEXT, lent_at TIMESTAMP NOT NULL DEFAULT NOW(), expected_return_date DATE NOT NULL, returned_at TIMESTAMP, return_checker VARCHAR(64), appearance_result VARCHAR(32), original_status VARCHAR(16) NOT NULL,
 plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL, created_by VARCHAR(64), updated_by VARCHAR(64), is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qms.instrument_maintenance_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instrument_id BIGINT NOT NULL, fault_description TEXT NOT NULL, finder_name VARCHAR(64), found_at TIMESTAMP, repair_vendor VARCHAR(128), repair_content TEXT, repair_cost NUMERIC(14,2), repair_date DATE, status VARCHAR(16) NOT NULL DEFAULT '维修中',
 plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL, created_by VARCHAR(64), updated_by VARCHAR(64), is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qms.instrument_scrap_record (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instrument_id BIGINT NOT NULL, scrap_reason TEXT NOT NULL, current_condition TEXT, disposal_method VARCHAR(32), applicant_name VARCHAR(64), metrology_approver VARCHAR(64), quality_approver VARCHAR(64), approved_at TIMESTAMP, status VARCHAR(16) NOT NULL DEFAULT '待审批',
 plant_code VARCHAR(8) NOT NULL, plant_name VARCHAR(32) NOT NULL, created_by VARCHAR(64), updated_by VARCHAR(64), is_deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_instrument_plant_status ON qms.measuring_instrument(plant_code,status,next_calibration_date);
CREATE INDEX IF NOT EXISTS idx_instrument_usage_batch ON qms.instrument_usage_record(product_batch_no,instrument_id);
INSERT INTO qms.sys_module(module_code,module_name,status,created_at,updated_at,is_deleted) SELECT 'measurement','计量管理','1',NOW(),NOW(),0 WHERE NOT EXISTS(SELECT 1 FROM qms.sys_module WHERE module_code='measurement' AND is_deleted=0);
INSERT INTO qms.sys_role_permission(role_code,module_code,action_code,created_at,updated_at,is_deleted) SELECT r.role_code,'measurement','VIEW',NOW(),NOW(),0 FROM qms.sys_role r WHERE r.is_deleted=0 AND NOT EXISTS(SELECT 1 FROM qms.sys_role_permission p WHERE p.role_code=r.role_code AND p.module_code='measurement' AND p.action_code='VIEW' AND p.is_deleted=0);
