-- 供应商基础评价与工装管理（仅 QMS 内部数据）

CREATE TABLE IF NOT EXISTS qms.supplier_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    assessment_period VARCHAR(16) NOT NULL,
    qualified_rate NUMERIC(6,2),
    defect_rate NUMERIC(6,2),
    rectification_rate NUMERIC(6,2),
    delivery_rate NUMERIC(6,2),
    compliance_rate NUMERIC(6,2),
    spc_assessment VARCHAR(32),
    grade VARCHAR(2),
    share_suggestion VARCHAR(64),
    audit_frequency VARCHAR(64),
    admission_suggestion VARCHAR(64),
    remark TEXT,
    plant_code VARCHAR(8) NOT NULL,
    plant_name VARCHAR(32) NOT NULL,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (supplier_id, assessment_period, plant_code)
);

CREATE TABLE IF NOT EXISTS qms.tooling_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tooling_code VARCHAR(64) NOT NULL,
    tooling_name VARCHAR(128) NOT NULL,
    tooling_type VARCHAR(32) NOT NULL,
    specification VARCHAR(128),
    applicable_product VARCHAR(128),
    applicable_process VARCHAR(128),
    material VARCHAR(64),
    supplier_name VARCHAR(128),
    purchase_date DATE,
    cost NUMERIC(14,2),
    version_no VARCHAR(32) NOT NULL DEFAULT 'V1.0',
    status VARCHAR(16) NOT NULL DEFAULT '在用',
    storage_location VARCHAR(128),
    keeper_name VARCHAR(64),
    life_limit INTEGER,
    used_count INTEGER NOT NULL DEFAULT 0,
    plant_code VARCHAR(8) NOT NULL,
    plant_name VARCHAR(32) NOT NULL,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (tooling_code, plant_code)
);

CREATE TABLE IF NOT EXISTS qms.tooling_maintenance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tooling_id BIGINT NOT NULL,
    record_type VARCHAR(16) NOT NULL,
    plan_cycle VARCHAR(16),
    due_date DATE,
    executed_date DATE,
    fault_description TEXT,
    repair_measure TEXT,
    acceptance_result VARCHAR(16),
    verification_result VARCHAR(16),
    status VARCHAR(16) NOT NULL DEFAULT '待执行',
    responsible_name VARCHAR(64),
    remark TEXT,
    plant_code VARCHAR(8) NOT NULL,
    plant_name VARCHAR(32) NOT NULL,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_supplier_assessment_plant_period ON qms.supplier_assessment (plant_code, assessment_period);
CREATE INDEX IF NOT EXISTS idx_tooling_asset_plant_status ON qms.tooling_asset (plant_code, status);
CREATE INDEX IF NOT EXISTS idx_tooling_maintenance_tooling ON qms.tooling_maintenance_record (tooling_id, record_type, due_date);

INSERT INTO qms.sys_module (module_code, module_name, status, created_at, updated_at, is_deleted)
SELECT 'tooling', '工装管理', '1', NOW(), NOW(), 0
WHERE NOT EXISTS (SELECT 1 FROM qms.sys_module WHERE module_code = 'tooling' AND is_deleted = 0);

INSERT INTO qms.sys_role_permission (role_code, module_code, action_code, created_at, updated_at, is_deleted)
SELECT r.role_code, 'tooling', 'VIEW', NOW(), NOW(), 0
FROM qms.sys_role r
WHERE r.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM qms.sys_role_permission p
      WHERE p.role_code = r.role_code AND p.module_code = 'tooling' AND p.action_code = 'VIEW' AND p.is_deleted = 0
  );
