-- 补充工装与产品/BOM/工艺路线关联、版本履历及一物一码。
ALTER TABLE qms.tooling_asset ADD COLUMN IF NOT EXISTS qr_code VARCHAR(160);
ALTER TABLE qms.tooling_maintenance_record ADD COLUMN IF NOT EXISTS root_cause TEXT;

CREATE TABLE IF NOT EXISTS qms.tooling_asset_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tooling_id BIGINT NOT NULL,
    binding_type VARCHAR(16) NOT NULL,
    product_code VARCHAR(64),
    product_name VARCHAR(128),
    bom_code VARCHAR(64),
    process_code VARCHAR(64),
    process_name VARCHAR(128),
    plant_code VARCHAR(8) NOT NULL,
    plant_name VARCHAR(32) NOT NULL,
    created_by VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    is_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS qms.tooling_version_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tooling_id BIGINT NOT NULL,
    version_no VARCHAR(32) NOT NULL,
    change_type VARCHAR(32) NOT NULL,
    change_description TEXT NOT NULL,
    effective_date DATE,
    changed_by VARCHAR(64),
    plant_code VARCHAR(8) NOT NULL,
    plant_name VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    is_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tooling_asset_qr_code ON qms.tooling_asset (qr_code) WHERE qr_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tooling_binding_tooling ON qms.tooling_asset_binding (tooling_id, is_deleted);
CREATE INDEX IF NOT EXISTS idx_tooling_version_tooling ON qms.tooling_version_record (tooling_id, created_at DESC);
